#!/bin/bash

echo "🔧 Fixing Copy Bundle Resources conflict..."

echo "📋 The error shows:"
echo "'The Copy Bundle Resources build phase contains this target's Info.plist file'"
echo ""
echo "This means Info.plist is being added to the Copy Bundle Resources phase,"
echo "which conflicts with the build settings reference."
echo ""
echo "🔧 Solution:"
echo "1. In Xcode, go to Project → Build Phases"
echo "2. Expand 'Copy Bundle Resources'"
echo "3. Look for 'Info.plist' in the list"
echo "4. If you see 'Info.plist', remove it (select and press Delete)"
echo "5. Clean and Build"
echo ""
echo "🎯 Why this happens:"
echo "- Info.plist should be referenced by build settings, not copied"
echo "- Having it in both places causes 'Multiple commands produce' error"
echo ""
echo "📋 Alternative if you can't find it:"
echo "1. Go to Project → Build Phases"
echo "2. Look for any duplicate Info.plist entries"
echo "3. Remove any Info.plist from Copy Bundle Resources"
echo "4. Make sure Info.plist is only referenced in Build Settings" 