#!/bin/bash

echo "🔧 Fixing Firebase dependencies..."

echo "📋 The error 'No such module FirebaseCore' means Firebase isn't properly added to the project."
echo ""
echo "🔧 Solution: Add Firebase Package Dependencies"
echo ""
echo "1. In Xcode, go to File → Add Package Dependencies"
echo "2. In the search bar, paste: https://github.com/firebase/firebase-ios-sdk.git"
echo "3. Click 'Add Package'"
echo "4. Select these products:"
echo "   - FirebaseCore"
echo "   - FirebaseStorage"
echo "5. Click 'Add Package'"
echo ""
echo "🎯 Alternative method:"
echo "1. In Xcode, select your project in the navigator"
echo "2. Select the 'Chiron' target"
echo "3. Go to 'General' tab"
echo "4. Scroll down to 'Frameworks, Libraries, and Embedded Content'"
echo "5. Click the '+' button"
echo "6. Search for 'Firebase'"
echo "7. Add FirebaseCore and FirebaseStorage"
echo ""
echo "📋 After adding dependencies:"
echo "1. Clean Build Folder (Cmd+Shift+K)"
echo "2. Build (Cmd+B)"
echo ""
echo "✅ Expected result:"
echo "- No more 'No such module FirebaseCore' errors"
echo "- Build succeeds"
echo "- Speech integration works" 